const ISO: Record<string, string> = {
  'África do Sul': 'za',
  'Alemanha': 'de',
  'Albânia': 'al',
  'Angola': 'ao',
  'Arábia Saudita': 'sa',
  'Argélia': 'dz',
  'Argentina': 'ar',
  'Austrália': 'au',
  'Áustria': 'at',
  'Bélgica': 'be',
  'Bermudas': 'bm',
  'Bolívia': 'bo',
  'Bósnia-Herzegovina': 'ba',
  'Brasil': 'br',
  'Cabo Verde': 'cv',
  'Camarões': 'cm',
  'Canadá': 'ca',
  'Catar': 'qa',
  'Chile': 'cl',
  'Colômbia': 'co',
  'Congo RD': 'cd',
  'Coreia do Sul': 'kr',
  'Costa do Marfim': 'ci',
  'Costa Rica': 'cr',
  'Croácia': 'hr',
  'Curaçao': 'cw',
  'Dinamarca': 'dk',
  'Egito': 'eg',
  'El Salvador': 'sv',
  'Equador': 'ec',
  'Escócia': 'gb-sct',
  'Espanha': 'es',
  'Estados Unidos': 'us',
  'França': 'fr',
  'Gana': 'gh',
  'Guatemala': 'gt',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hungria': 'hu',
  'Ilhas Faroé': 'fo',
  'Inglaterra': 'gb-eng',
  'Irão': 'ir',
  'Iraque': 'iq',
  'Irlanda': 'ie',
  'Islândia': 'is',
  'Itália': 'it',
  'Jamaica': 'jm',
  'Japão': 'jp',
  'Jordânia': 'jo',
  'Mali': 'ml',
  'Marrocos': 'ma',
  'México': 'mx',
  'Nigéria': 'ng',
  'Noruega': 'no',
  'Nova Zelândia': 'nz',
  'Países Baixos': 'nl',
  'Panamá': 'pa',
  'Paraguai': 'py',
  'Peru': 'pe',
  'Polónia': 'pl',
  'Portugal': 'pt',
  'Rep. Checa': 'cz',
  'República Dominicana': 'do',
  'Roménia': 'ro',
  'Senegal': 'sn',
  'Sérvia': 'rs',
  'Suécia': 'se',
  'Suíça': 'ch',
  'Tunísia': 'tn',
  'Turquia': 'tr',
  'Ucrânia': 'ua',
  'Uruguai': 'uy',
  'Usbequistão': 'uz',
  'Venezuela': 've',
}

export function codigoPais(nome: string): string | null {
  return ISO[nome] ?? null
}

export function urlBandeira(nome: string, tamanho: 40 | 80 = 40): string | null {
  const cod = ISO[nome]
  if (!cod) return null
  return `https://flagcdn.com/w${tamanho}/${cod}.png`
}
